_BASE_: "/home/leon/OWOD/configs/Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: 'detectron2://ImageNetPretrained/MSRA/R-50.pkl'
DATASETS:
  TRAIN: ('train_SODA', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('val_SODA', )   # voc_coco_2007_test, t1_voc_coco_2007_test, t1_voc_coco_2007_val
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 20100
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/runs_SODA_1"
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 6
  COMPUTE_ENERGY: True