_BASE_: "/home/leon/OWOD_new/configs/Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ('train_CODA', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('val_CODA', )   # voc_coco_2007_test, t1_voc_coco_2007_test, t1_voc_coco_2007_val
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 10000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/home/leon/OWOD_new/output/runs_CODA_FPN"
OWOD:
  COMPUTE_ENERGY: True
  ENERGY_SAVE_PATH: 'energy'
  PREV_INTRODUCED_CLS: 6
  CUR_INTRODUCED_CLS: 74